import type { Metadata } from 'next';

import { fontVariables } from '@/lib/fonts';

import './globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(fontVariables, 'h-full', 'antialiased')}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
