// Thanks to Fumadocs.
// Reference: https://github.com/fuma-nama/fumadocs/blob/0e2b5b666c4d7a43ec49b594a901b7ccdf7cdcbd/packages/base-ui/src/components/codeblock.tsx
'use client';

import {
  useRef,
  type ComponentProps,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
} from 'react';
import { PiCheck, PiClipboard } from 'react-icons/pi';

import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { useCopyButton } from '@/utils/use-copy-button';

export interface CodeBlockProps extends ComponentProps<'figure'> {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  'data-line-numbers'?: boolean;

  /**
   * @defaultValue 1
   */
  'data-line-numbers-start'?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

export function Pre(props: ComponentProps<'pre'>) {
  return (
    <pre
      {...props}
      className={cn('min-w-full w-max *:flex *:flex-col', props.className)}
    >
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn('empty:hidden', props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const areaRef = useRef<HTMLDivElement>(null);

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        'shiki relative overflow-hidden',
        'my-4 rounded-xl',
        'border border-border',
        'text-sm',
        'bg-code',
        keepBackground && 'bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)',
        'not-prose',
        props.className,
      )}
    >
      {title ? (
        <div
          className={cn(
            'flex items-center gap-2 h-9.5',
            'px-4',
            'bg-code-bar',
            'border-b border-border',
            'text-foreground/80',
          )}
        >
          {typeof icon === 'string' ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            className: '-me-2',
            children: allowCopy && <CopyButton containerRef={areaRef} />,
          })}
        </div>
      ) : (
        Actions({
          className: cn(
            'absolute top-2 right-2 z-2',
            'rounded-lg',
            'text-muted-foreground',
            'backdrop-blur-lg',
          ),
          children: allowCopy && <CopyButton containerRef={areaRef} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        role="region"
        className={cn(
          'overflow-auto max-h-[600px]',
          'py-3.5',
          'text-[0.8125rem]',
          'fd-scroll-container',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring',
          viewportProps.className,
        )}
        style={
          {
            // space for toolbar
            '--padding-right': !title ? 'calc(var(--spacing) * 8)' : undefined,
            counterSet: props['data-line-numbers']
              ? `line ${Number(props['data-line-numbers-start'] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as object
        }
      >
        {children}
      </div>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
}: {
  className?: string;
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName('pre').item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll('.nd-copy-ignore').forEach((node) => {
      node.replaceWith('\n');
    });

    void navigator.clipboard.writeText(clone.textContent ?? '');
  });

  return (
    <Button
      variant="outline"
      size="xs"
      isLabelHidden={true}
      label={checked ? 'Copied' : 'Copy code'}
      icon={checked ? <PiCheck /> : <PiClipboard />}
      tooltip={checked ? 'Copied!' : 'Copy code'}
      onClick={onClick}
      className={className}
    />
  );
}
